# Generated by Django 2.0.6 on 2018-07-05 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_base',
            options={'ordering': ['username', 'last_update_date', 'last_updated_by']},
        ),
        migrations.RenameField(
            model_name='role_base',
            old_name='Created_By',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='role_base',
            old_name='Creation_Date',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='role_base',
            old_name='Last_Update_Date',
            new_name='last_update_date',
        ),
        migrations.RenameField(
            model_name='role_base',
            old_name='Last_Updated_By',
            new_name='last_updated_by',
        ),
        migrations.RenameField(
            model_name='role_base',
            old_name='Role_Name',
            new_name='role_name',
        ),
        migrations.RenameField(
            model_name='user_base',
            old_name='Created_By',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='user_base',
            old_name='Creation_Date',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='user_base',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user_base',
            old_name='Is_Active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='user_base',
            old_name='Last_Update_Date',
            new_name='last_update_date',
        ),
        migrations.RenameField(
            model_name='user_base',
            old_name='Last_Updated_By',
            new_name='last_updated_by',
        ),
        migrations.RenameField(
            model_name='user_base',
            old_name='Password',
            new_name='passowrd',
        ),
        migrations.RenameField(
            model_name='user_base',
            old_name='User_Name',
            new_name='username',
        ),
    ]
