# Generated by Django 2.0.6 on 2018-06-29 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180628_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_base',
            options={'ordering': ['User_Name', 'Last_Update_Date', 'Last_Updated_By']},
        ),
    ]
