# Generated by Django 2.0.6 on 2018-07-05 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180705_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_base',
            old_name='passowrd',
            new_name='password',
        ),
    ]
