# Generated by Django 2.0.6 on 2018-06-29 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180629_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_base',
            name='Last_Update_Date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
