# Generated by Django 2.0.6 on 2018-07-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180705_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role_base',
            name='role_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user_base',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user_base',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
