# Generated by Django 2.0.6 on 2018-06-29 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180629_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role_base',
            name='Last_Update_Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user_base',
            name='Last_Update_Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
