# Generated by Django 2.0.6 on 2018-07-03 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180629_1019'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Role_Base',
            new_name='RoleBase',
        ),
        migrations.RenameModel(
            old_name='User_Base',
            new_name='UserBase',
        ),
    ]
