# Generated by Django 2.0.6 on 2018-07-03 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180703_1414'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoleBase',
            new_name='Role_Base',
        ),
        migrations.RenameModel(
            old_name='UserBase',
            new_name='User_Base',
        ),
    ]
