# Generated by Django 2.0.6 on 2018-07-09 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180709_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='role_base',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
