# Generated by Django 2.0.6 on 2018-07-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180703_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_base',
            name='Is_Active',
            field=models.CharField(default='Y', max_length=2),
        ),
    ]
