# Generated by Django 2.0.6 on 2018-07-04 08:21

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('app', '0008_user_base_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
            ],
            options={
                'ordering': ('username',),
                'managed': False,
                'proxy': True,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='user_base',
            old_name='Email_Addr',
            new_name='Email',
        ),
    ]
