# Generated by Django 2.0.6 on 2018-07-09 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_role',
            old_name='role_id',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='user_role',
            old_name='user_id',
            new_name='user',
        ),
    ]
