# Generated by Django 2.0.6 on 2018-07-10 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_user_base_roles'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user_role',
            unique_together={('user', 'role')},
        ),
    ]
